version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_DATABASE: reactlibrarydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: test1234!
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/react-library
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234!
      MYSQL_DATABASE: reactlibrarydatabase
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
